export const DEMO_CATEGORIES = [
  { id: '1', name: 'Подарунки ручної роботи', slug: 'handmade-gifts' },
  { id: '2', name: 'Сувеніри та декор', slug: 'souvenirs-decor' },
  { id: '3', name: 'Творчі набори', slug: 'craft-kits' },
  { id: '4', name: 'Дитячі іграшки', slug: 'toys' },
];

export const DEMO_PRODUCTS = [
  {
    id: 'p1',
    name: 'Подарунковий бокс «Теплий вечір»',
    slug: 'gift-box-warm-evening',
    sku: 'CS-GIFT-01',
    price: 750,
    stock: 12,
    category_id: '1',
    category_name: 'Подарунки ручної роботи',
    brand: 'CreaSphere',
    material: 'Крафтовий картон, натуральний віск',
    dimensions: '20 × 20 × 10 см',
    weight: '650 г',
    description: 'Святковий подарунковий набір ручної роботи: авторська соєва ароматична свічка, добірний крафтовий чай, свіже імбирне печиво та дизайнерська листівка.',
    images: ['/gift_collection.webp', '/hero_products.webp'],
  },
  {
    id: 'p2',
    name: 'Керамічна чашка «Павлоградські світанки»',
    slug: 'ceramic-cup-pavlograd',
    sku: 'CS-CER-02',
    price: 380,
    stock: 8,
    category_id: '2',
    category_name: 'Сувеніри та декор',
    brand: 'КреаСфера Арт',
    material: 'Глина, керамічна глазур',
    dimensions: '350 мл',
    weight: '320 г',
    description: 'Ексклюзивна чашка з авторським розписом ручної роботи, створена у нашій керамічній майстерні. Приємна на дотик, витримує гарячі напої.',
    images: ['/gallery1.jpg', '/gallery2.jpg'],
  },
  {
    id: 'p3',
    name: 'Набір для творчості «Юний Скульптор»',
    slug: 'kit-young-sculptor',
    sku: 'CS-KIT-03',
    price: 520,
    stock: 15,
    category_id: '3',
    category_name: 'Творчі набори',
    brand: 'CreaSphere Kids',
    material: 'Глина, дерево, акрил',
    dimensions: '25 × 18 × 8 см',
    weight: '1200 г',
    description: 'Повний набір матеріалів для ліплення власної керамічної фігурки вдома. Включає спеціальну глину, набір стеків, акрилові фарби та пензлики.',
    images: ['/kids_workshop.webp', '/workshop1.jpg'],
  },
  {
    id: 'p4',
    name: 'Текстильний ведмедик «Тіммі»',
    slug: 'textile-bear-timmy',
    sku: 'CS-TOY-04',
    price: 640,
    stock: 5,
    category_id: '4',
    category_name: 'Дитячі іграшки',
    brand: 'Майстерня CreaSphere',
    material: '100% бавовна, гіпоалергенний наповнювач',
    dimensions: 'Висота 28 см',
    weight: '240 г',
    description: 'Чарівний м’який ведмедик ручної роботи. Безпечний для найменших, кожна деталь надійно пришита. Стане чудовим подарунком малюку.',
    images: ['/hero_products.webp', '/gallery4.jpg'],
  },
  {
    id: 'p5',
    name: 'Ароматична свічка «Лавандовий сад»',
    slug: 'candle-lavender-garden',
    sku: 'CS-CND-05',
    price: 320,
    stock: 20,
    category_id: '2',
    category_name: 'Сувеніри та декор',
    brand: 'CreaSphere Home',
    material: '100% соєвий віск, олії Провансу',
    dimensions: '200 мл',
    weight: '380 г',
    description: 'Ароматична свічка в баночці з бурштинового скла з дерев’яним гнотом, що затишно потріскує під час горіння. До 40 годин чистого аромату.',
    images: ['/gallery3.jpg', '/gallery5.jpg'],
  },
  {
    id: 'p6',
    name: 'Набір для створення картини з мозаїки',
    slug: 'kit-mosaic-art',
    sku: 'CS-KIT-06',
    price: 690,
    stock: 7,
    category_id: '3',
    category_name: 'Творчі набори',
    brand: 'CreaSphere',
    material: 'Дерево, кольорове скло, кераміка',
    dimensions: '20 × 20 см',
    weight: '900 г',
    description: 'Захоплюючий арт-набір для створення панно з вітражного та керамічного скла. Розвиває дрібну моторику та творчу уяву.',
    images: ['/craft_hands.webp', '/workshop2.jpg'],
  },
];
